# Generated by Django 5.1.6 on 2025-02-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='plc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
