# Generated by Django 5.1.6 on 2025-02-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
