# Generated by Django 5.1.6 on 2025-02-27 19:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_destination_img_alter_popular_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
